[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "loss-landscape-3d"
version = "0.1.0"
description = "A library for sampling weight spaces and visualizing PyTorch model loss landscapes and optimization trajectories in interactive 3D."
authors = [
    { name = "Arnav Agarwal" }
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "torch>=1.9.0",
    "numpy>=1.20.0",
    "plotly>=5.0.0",
    "matplotlib>=3.4.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]

[project.urls]
Homepage = "https://github.com/ArnavAgarwal-Mr-AR/loss-landscape-3d"
Repository = "https://github.com/ArnavAgarwal-Mr-AR/loss-landscape-3d"
"Bug Tracker" = "https://github.com/ArnavAgarwal-Mr-AR/loss-landscape-3d/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["loss_landscape_3d*"]
